name: Deploy to AWS ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up environment variables
        run: |
          echo "FLASK_SECRET=${{ secrets.FLASK_SECRET }}" >> $GITHUB_ENV
          echo "OIDC_CLIENT_ID=${{ secrets.OIDC_CLIENT_ID }}" >> $GITHUB_ENV
          echo "OIDC_CLIENT_SECRET=${{ secrets.OIDC_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Deploy with Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.0
      - run: terraform init -chdir=infra
      - run: terraform apply -chdir=infra -auto-approve
